### ISSUE TITLE
未找到 pages/index/index.wxml 文件

### ISSUE THREAD

**Issue by iwantacook** [BruceZhang1993/wechat_web_devtools#5]
未找到 pages/index/index.wxml 文件 
 > 0 pages/index/index
这样的错误提示，请问如何处理呢？

**Comment by BruceZhang1993** [comment]
使用终端进入项目目录，执行 ./nw 是否能在终端看到更详细的出错信息或者 Traceback.

**Comment by iwantacook** [comment]
谢谢，我重装了整个系统，我再试试。

**Comment by iwantacook** [comment]
谢谢，我重装了一次系统，我再试试。 @BruceZhang1993

**Comment by iwantacook** [comment]
`/home/yangwj/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/yangwj/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/yangwj/.config/微信web开发者工具/WeappVendor/wcc.exe: 5: /home/yangwj/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")

**Comment by iwantacook** [comment]
permission denied, mkdir '/home/yangwj/.config'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Function.mkdir.sync (/opt/tencent/wechat_web_devtools/node_modules/mkdir-p/index.js:22:8)
    at Function.mkdir.sync (/opt/tencent/wechat_web_devtools/node_modules/mkdir-p/index.js:21:11)
    at Function.mkdir.sync (/opt/tencent/wechat_web_devtools/node_modules/mkdir-p/index.js:21:11)
    at init (/opt/tencent/wechat_web_devtools/app/dist/config/dirConfig.js:1:232)
    at Object.<anonymous> (/opt/tencent/wechat_web_devtools/app/dist/config/dirConfig.js:1:980)
    at Module._compile (module.js:580:32)
    at Object.Module._extensions..js (module.js:595:10)
    at Module.load (module.js:497:32)

**Comment by iwantacook** [comment]
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/home/yangwj/.config'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Function.mkdir.sync (/opt/tencent/wechat_web_devtools/node_modules/mkdir-p/index.js:22:8)
    at Function.mkdir.sync (/opt/tencent/wechat_web_devtools/node_modules/mkdir-p/index.js:21:11)
    at Function.mkdir.sync (/opt/tencent/wechat_web_devtools/node_modules/mkdir-p/index.js:21:11)
    at init (/opt/tencent/wechat_web_devtools/app/dist/config/dirConfig.js:1:232)
    at Object.<anonymous> (/opt/tencent/wechat_web_devtools/app/dist/config/dirConfig.js:1:980)
    at Module._compile (module.js:580:32)
    at Object.Module._extensions..js (module.js:595:10)
    at Module.load (module.js:497:32)

我已经完全修改的项目文件的读写权限和所有者权限，还是如上提示。

**Comment by iwantacook** [comment]
这个是执行sudo ./nw后的提示 @BruceZhang1993
